spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/unsolved_wa?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

sample:
  value: default
