name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:   
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build docker
      run: ./gradlew bootBuildImage
    - name: Docker Hub Sign-in
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker Image
      run: docker push $REPO
