name: Publish Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
    - uses: actions/checkout@v3
    - name: extract version from commit message
      run: |
        VERSION=$(grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" <<< "${{ github.event.head_commit.message }}")
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: create Github release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build docker
      run: ./gradlew bootBuildImage --imageName=unsolvedwa/backend-api
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker Image
      run: |
        docker push $REPO
        docker tag $REPO $REPO:${{ env.VERSION }}
        docker push $REPO:${{ env.VERSION }}
